### ISSUE TITLE
Mention the need for a githubissue port in documentation

### ISSUE THREAD

**Issue by nicolagi** [rsc/github#5]
I got a panic while running `issue -a`.

This line failed to print the error message https://github.com/rsc/github/blob/master/issue/acme.go#L70. I eventually figured I had to add

```
plumb to githubissue
```
to ~/lib/plumbing but that's not in the documentation. The panic trace is similar to the below (similar because line number is influenced by some print's I've added).

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x230 pc=0x7b6509]

goroutine 21 [running]:
9fans.net/go/acme.(*Win).Err(...)
	/home/nicolagi/go/pkg/mod/9fans.net/go@v0.0.2/acme/acme.go:895
main.(*awin).plumbserve(0xc0000a8480)
	/home/nicolagi/go/src/rsc.io/github/issue/acme.go:71 +0x149
created by main.acmeMode
	/home/nicolagi/go/src/rsc.io/github/issue/acme.go:62 +0x1f7
```

**Comment by yarikk** [comment]
@rsc true ☝🏻
